lib/cup_web/router.ex
defmodule CupWeb.Router do
  use CupWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_root_layout, {CupWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CupWeb.Auth    # auth.ex module plug - add :curent_member to conn.assigns
    # we want to find if member is logged to obtain access to :index & :show actions
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CupWeb do
    pipe_through :browser
                           # index route stores :index in conn
    get "/",               PageController, :index  # match URL & send to controller
    resources "/members",  MemberController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end


  # Other scopes may use custom stacks.
  # scope "/api", CupWeb do
  #   pipe_through :api
  # end
end

lib/cup_web/views/layout_view.ex
defmodule CupWeb.LayoutView do
  use CupWeb, :view

  def title() do
    "Salt and Light"
  end
  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  #@compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/cup_web/templates/layout/app.html.eex
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, member-scalable=no" />
    <title>Rumbl · Phoenix Framework</title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
<section class="container">
  <nav role="navigation">
    <ul>
      <%= if @current_member do %>
        <li><%= @current_member.membername %></li>
        <li>
          <%= link "Log out",
                to: Routes.session_path(@conn, :delete, @current_member),
                method: "delete" %>
        </li>
      <% else %>
        <li><%= link "Register", to: Routes.member_path(@conn, :new) %></li>

      <% end %>
    </ul>
  </nav>

  <a href="http://phoenixframework.org/" class="phx-logo">
    <img src="<%= Routes.static_url(@conn, "/images/phoenix.png") %>"
      alt="Phoenix Framework Logo"/>
    </a>
</section>
    </header>
      <main role="main" class="container">
        <p class="alert alert-info" role="alert">
           <%= get_flash(@conn, :info) %>
        </p>
        <p class="alert alert-danger" role="alert">
           <%= get_flash(@conn, :error) %>
        </p>
        <%= @inner_content %>
      </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"</script>

     <script>window.memberToken = "<%= assigns[:member_token] %>"</script>

  </body>
</html>

lib/cup_web/templates/layout/live.html.eex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/cup_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Cup", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt=""/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>